/*
 * generated by Xtext 2.13.0
 */
package de.htwg.modellgetriebene


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PixelTankWarDslStandaloneSetup extends PixelTankWarDslStandaloneSetupGenerated {

	def static void doSetup() {
		new PixelTankWarDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
